### ISSUE TITLE
[FIX] 인증이 필요한 endpoint AccessDenied 오류 해결 

### ISSUE THREAD

**Issue by sharpie1330** [yoonhaorg/Duktown_Backend#10]
## 🔥 Fix Issue
현재 로그인/회원가입을 제외한 모든 인증이 필요한 endPoint에 대해 AccessDenied 오류가 발생합니다.
이는 JWT 토큰으로부터 유저 정보를 제대로 얻어오지 못하고 있기 때문인데, 현재 userService에서 토큰 발급 메소드에 잘못된 파라미터를 입력하는 것이 원인입니다. 이를 수정합니다.

또한 인증이 필요한 endPoint에 대해 Controller에서 JWT 토큰으로부터 유저 정보를 획득할 수 있도록 수정하고, 추가적으로 login 시 필요한 아이디, 비밀번호를 파라미터로 받지 않고 DTO를 통해 받을 수 있도록 수정합니다.

## ✅ TODO
 - [x] @AuthenticationPrincipal 어노테이션으로 UserDetails 객체를 받아와 사용자 아이디를 얻을 수 있도록 수정
 - [x] UserService 코드 오류 수정
 - [x] login 시 loginId, password를 parameter가 아닌 DTO로 받도록 수정
