### ISSUE TITLE
[FEAT] 좋아요 기능 구현

### ISSUE THREAD

**Issue by sharpie1330** [yoonhaorg/Duktown_Backend#17]
## 🔥 Feature Issue
좋아요와 관련된 기능을 구현합니다. 
- 익명 게시판을 기반으로 구현하므로, 좋아요한 사람들 목록 조회 등은 구현하지 않습니다.
- 다만, 현재 로그인한 사용자가 게시글/댓글에 대해 좋아요한 여부 표시에 대한 기능은 구현합니다.
- 좋아요는 추가 및 취소로만 작동하므로 수정 또한 구현하지 않습니다.
- 테스트 코드는 나중에 따로 작성합니다.

## ✅ TODO
 - [x] 좋아요 추가/취소 구현
 - [x] 댓글 삭제 시 좋아요도 함께 삭제
 - [x] deleted가 true인 댓글은 좋아요하지 못하도록 구현
 - [x] 게시글, 댓글에 좋아요 여부, 개수 표시되도록 수정 
 -> 댓글은 완료하였고, 게시글은 일상, 장터 하나로 합치는 작업 이후 진행 예정

**Comment by sharpie1330** [comment]
게시글 좋아요 시 게시글 좋아요 여부, 개수 표시되도록 구현하는 작업은 일상, 장터 통합 후 작업

**Comment by sharpie1330** [comment]
위의 eb55a3f 커밋은 reset한 커밋입니다.

**Comment by sharpie1330** [comment]
- [x] 일상, 장터를 Post로 하나로 합치면서 Post에 Like 연관관계 추가
- [x] PostResponse 시 liked, likeCount 반환하도록 수정작업 필요
- [x] 배달팟은 좋아요 안됨 -> 수정

이러한 사유로 issue 재오픈

**Comment by sharpie1330** [comment]
- [x] 게시글 삭제 시 좋아요도 삭제되도록 코드 추가
