### ISSUE TITLE
[REFACTOR] DB 변경 및 auto_increment 전략 변경

### ISSUE THREAD

**Issue by sharpie1330** [yoonhaorg/Duktown_Backend#27]
## 🔥 Refactor Issue
- 로컬 테스트 DB를 H2에서 MySQL로 변경합니다.
- Entity 클래스의 id에 적용된 GeneratedValue 어노테이션의 옵션을 IDENTITY로 변경합니다.

## ✅ TODO
 - [x] build.gradle mysql 의존성 추가 및 h2 의존성 삭제
 - [x] application.yml에 mysql 연결 설정 추가 및 h2 설정 삭제
 - [x] Entity 클래스 GeneratedValue 옵션 IDENTITY로 변경
