### ISSUE TITLE
[FEAT] 회원가입/로그인 기능 구현

### ISSUE THREAD

**Issue by sharpie1330** [yoonhaorg/Duktown_Backend#3]
## 🔥 Feature Issue
회원가입/로그인 기능 구현

## ✅ TODO
 - [x] 회원가입 쿼리 구현
 - [x] 이메일 중복 체크 기능 구현
 - [x] 아이디 중복 체크 기능 구현
 - [x] 필수 칼럼 값 입력 x 시 예외처리 (유효성 체크)
 - [x] 로그인 기능 구현
 - [x] SecurityConfig 설정
 - [x] UserDetails, UserDetailsService 및 인증 필터 구현
 - [x] JWT의존성 추가, JWT Token 발급 로직 구현
 - [x] 테스트코드 작성 (unit test)
