### ISSUE TITLE
[FEAT] 2단계 인증 기능 구현

### ISSUE THREAD

**Issue by sharpie1330** [yoonhaorg/Duktown_Backend#30]
## 🔥 Feature Issue
기숙사생, 관리자 인증 기능을 개발합니다.
인증 완료 시 사용자의 권한이 변경됩니다.

## ✅ TODO
 - [ ] 기숙사 인증신청 로직 구현
 - [ ] 기숙사 인증신청 목록 조회 구현(관리자)
 - [ ] 기숙사 인증신청 목록 상세 조회 구현(관리자)
 - [ ] 기숙사 인증신청 처리(승인/거절) 구현(관리자)
