### ISSUE TITLE
[FEAT] 배달팟, 채팅 기능 개발

### ISSUE THREAD

**Issue by sharpie1330** [yoonhaorg/Duktown_Backend#41]
## 🔥 Feature Issue
- 배달팟 + 채팅 기능을 개발합니다.

## ✅ TODO
 - 배달팟 기능 구현
   - [x] 배달팟 생성
   - [x] 배달팟 삭제
   - [x] 배달팟 마감
   - [x] 배달팟 목록조회
   - [x] 배달팟 상세조회
 - 채팅 기능 구현
   - [x] 채팅방 생성
   - [x] 채팅방 입장(초대)
   - [x] 채팅방 채팅 내역 조회
   - [x] 채팅방 나가기
   - [x] 채팅 보내기
   - [ ] 이미지 보내기
   - [x] 내가 참여중인 채팅방 목록 가져오기
   - [x] 사용자 내보내기(재입장 불가)
- [x] 댓글 연결

**Comment by sharpie1330** [comment]
배달팟 생성 시 채팅방도 동시에 개설되어야 한다.
댓글로 참여 의사를 남기면, 배달팟 작성자가 해당 댓글 작성자를 초대할 수 있음.

**Comment by sharpie1330** [comment]
배달팟 생성 시 채팅방이 동시에 생성되는데, 이때 방장은 자동으로 채팅방에 입장되도록 구현
채팅방에 들어오는 인원들은 들어온 순서대로 숫자가 부여되어 "익명n"으로 이름이 보여짐
방장임을 구별하기 위해 방장의 숫자는 0으로 기본 지정

**Comment by sharpie1330** [comment]
채팅 조회는 들어온 시점부터 되어야 한다. 현재 들어온 시점 상관 없이 참여한 채팅방의 모든 채팅이 조회되고 있어 해당 부분 수정해야 함.

**Comment by sharpie1330** [comment]
돈과 관련된 내용이므로 배달팟은 삭제 처리되나 실제로 db에서 삭제되지 않음.

**Comment by sharpie1330** [comment]
글쓴이가 **님을 내보냈습니다. -> 다음과 같은 알림 채팅은 userId null로 전송됨

**Comment by sharpie1330** [comment]
페이징 처리해야함

**Comment by sharpie1330** [comment]
- 글쓴이가 **님을 내보냈습니다. -> 다음과 같은 알림 채팅은 userId null로 전송됨
- 모집 종료 시 배달팟 자동으로 삭제됨.
- chatType 추가 : JOIN, CHAT, EXIT, ORDER_FINISH, ACCOUNT_EDIT, WRITER_EXIT, FORCE_OUT
- 비활성화된(모집 종료 또는 주문 완료) 배달팟에는 사용자 초대 불가하도록 코드 수정

- [ ] 페이징 처리해야함.
- [x] 내보내기 되었어도 채팅 내역은 남아있도록 변경
