### ISSUE TITLE
[FEAT] 청소배정/완료/확인

### ISSUE THREAD

**Issue by Hwater00** [yoonhaorg/Duktown_Backend#44]
## 🔥 Feature Issue
- 유닛 및 사생회 기반
청소 배정 ,청소 완료, 청소 확인 기능 구현

## ✅ TODO
 - [x] initDB설정해서 유닛 생성하기
 - [x] 유닛 장이 청소 배정
 - [x] 날짜별 청소 담당자 조회
 - [x] 사생 청소 완료 신청
 - [x] 사생회 청소 완료 승인
