### ISSUE TITLE
[FEAT] 대타: 청소일정 조회 / 청소 유닛 자동 배정 로직 

### ISSUE THREAD

**Issue by Hwater00** [yoonhaorg/Duktown_Backend#57]
## 🔥 Feature Issue
배포를 위한 청소 배정, 유닛 배정 initDB 가상 데이터 추가
일정 별 청소 조회 부분에서 프론트 요청 반영: 기간 별 로그인 유저의 청소 일정만 조회로 기능 변경

## ✅ TODO
 - [x] 유저 가상 데이터 추가
 - [x] 가상 데이터 유닛그룹 배정
 - [x] 청소 가상 배정
