### ISSUE TITLE
[FEAT] 마이페이지 기능 구현 - 회원탈퇴, 회원 프로필 조회

### ISSUE THREAD

**Issue by sharpie1330** [yoonhaorg/Duktown_Backend#63]
## 🔥 Feature Issue
배포 전 최종 점검 및
회원탈퇴, 회원 프로필 조회 기능을 구현합니다.

## ✅ TODO
 - [x] 채팅방 나가기 시 배달팟, 채팅방 참여 인원이 줄어들지 않던 문제 해결
 - [x] 회원 프로필 조회 시 유닛 정보 및 유닛 역할 조회해야 함
 - [x] 회원 탈퇴 기능 구현

**Comment by sharpie1330** [comment]
- 회원 프로필 조회 시 유닛 정보 조회되는 부분도 작성 완료

회원탈퇴
- 게시글 -> 탈퇴한 회원 게시글은 조회되지 않음
- 댓글 -> 탈퇴한 회원의 경우 '알수없음'으로 표시됨(userId = null로 반환)
- 배달팟 -> 탈퇴한 회원 게시글은 조회되지 않음
- 채팅방 -> 탈퇴 시 채팅방 나가기 처리됨 "(알수없음)님이 나갔습니다."
- 채팅 -> 탈퇴 후 채팅 조회 시 채팅 보낸 사람 정보 userNumber = 알수없음,  userId = null

**Comment by sharpie1330** [comment]
2024-01-21기준
외박신청, 수리요청, 유닛, 청소 부분에서 본인일 경우에만 조회가 가능한 부분들밖에 없는것으로 파악됨
따라서 위에 작성한 comment 내용까지만 처리하고, 회원탈퇴 기능 마무리
