### ISSUE TITLE
[FIX] 배포 전 테스트에서 발견한 문제들 수정

### ISSUE THREAD

**Issue by sharpie1330** [yoonhaorg/Duktown_Backend#65]
## 🔥 Fix Issue
배포 전 테스트에서 발견한 문제들을 수정합니다.

## ✅ TODO
 - [x] 모집종료 다시 눌렀을 때 이미 모집을 종료한 채팅방입니다 예외 처리
 - [x] 모집 종료 시 모집 종료 채팅 전송
 - [x] 댓글 삭제 후 다른 댓글을 달면 작성자 이름이 (삭제)로 표시되는 문제 해결
 - [ ] RDS 연결
 - [x] 청소 담당일에만 청소 완료 요청 가능하도록 수정
 - [x] jasypt로 yml 프로퍼티 암호화
